name: Build & Test
on:
  push:
    branches: 
      - test/*
  pull_request:
    branches:
      - master

jobs:

  linux-windows-build:
    name: Linux & Windows Build
    runs-on: ubuntu-latest
    steps:

    - name: Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go
    
    - name: OS Packages 
      run: |
        sudo apt-get update --fix-missing && sudo apt-get -y install \
        git build-essential zlib1g zlib1g-dev wget zip unzip \
        mingw-w64 binutils-mingw-w64 g++-mingw-w64

    - name: Protoc
      env:
        PROTOC_VER: 3.11.4
      run: |
        wget -O protoc-${PROTOC_VER}-linux-x86_64.zip https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VER}/protoc-${PROTOC_VER}-linux-x86_64.zip \
        && unzip protoc-${PROTOC_VER}-linux-x86_64.zip \
        && sudo cp -vv ./bin/protoc /usr/local/bin/protoc

    - name: Protoc-gen-go
      env:
        PROTOC_GEN_GO_VER: 1.3.5
      run: |
        wget -O protoc-gen-go.tar.gz https://github.com/golang/protobuf/archive/v${PROTOC_GEN_GO_VER}.tar.gz \
        && tar xvf protoc-gen-go.tar.gz \
        && cd protobuf-${PROTOC_GEN_GO_VER} \
        && make install

    - name: Packr
      run: go get -u github.com/gobuffalo/packr/packr

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Go Assets
      run: ./go-assets.sh

    - name: Make
      run: export PATH=/home/runner/go/bin/:$PATH && make static-linux

    - name: Test
      run: ./sliver-server unpack --force && ./go-tests.sh

    - name: Linux Artifact
      uses: actions/upload-artifact@v2
      with:
        name: sliver-server_linux
        path: ./sliver-server

    - name: Make Windows
      run: export PATH=/home/runner/go/bin/:$PATH && make static-windows
  
    - name: Windows Artifact
      uses: actions/upload-artifact@v2
      with:
        name: sliver-server_windows.exe
        path: ./sliver-server.exe

  macos-build:
    name: MacOS Build
    runs-on: macos-latest
    steps:

    - name: Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Mingw
      run: brew install mingw-w64

    - name: Protoc
      env:
        PROTOC_VER: 3.11.4
      run: |
        wget -O protoc-${PROTOC_VER}-osx-x86_64.zip https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VER}/protoc-${PROTOC_VER}-osx-x86_64.zip \
        && unzip protoc-${PROTOC_VER}-osx-x86_64.zip \
        && sudo cp -vv ./bin/protoc /usr/local/bin/protoc

    - name: Protoc-gen-go
      env:
        PROTOC_GEN_GO_VER: 1.3.5
      run: |
        wget -O protoc-gen-go.tar.gz https://github.com/golang/protobuf/archive/v${PROTOC_GEN_GO_VER}.tar.gz \
        && tar xvf protoc-gen-go.tar.gz \
        && cd protobuf-${PROTOC_GEN_GO_VER} \
        && make install

    - name: Packr
      run: go get -u github.com/gobuffalo/packr/packr

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Go Assets
      run: ./go-assets.sh

    - name: Make
      run: export PATH=/Users/runner/go/bin/:$PATH && make static-macos

    - name: Test
      env:
        SLIVER_CC_32: /usr/local/bin/i686-w64-mingw32-gcc
        SLIVER_CC_64: /usr/local/bin/x86_64-w64-mingw32-gcc
      run: ./sliver-server unpack --force && ./go-tests.sh

    - name: MacOS Artifact
      uses: actions/upload-artifact@v2
      with:
        name: sliver-server_macos
        path: ./sliver-server

#
# > Integration Tests
#

  linux-ci:
    needs: linux-windows-build
    runs-on: ubuntu-latest
    name: Linux CI

    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: '14'
    - run: npm install -g ts-node typescript

    - uses: actions/checkout@master
      with:
        repository: moloch--/sliver-ci
    - name: NPM Install
      run: npm install

    - uses: actions/download-artifact@v2
      with:
        name: sliver-server_linux
        path: sliver-server

    - name: CI Tests
      run: ts-node ./index.ts
